remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins

title: Markdown Formatted Page
description: Yangsy56302's pages on Github
show_downloads: true